name: Spotless and Build

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    branches: [main, development]

jobs:
  build:
    strategy:
      matrix:
        java: [21]
        os: [ubuntu-latest]
    if: |
      ! github.event.pull_request.draft &&
      (github.event_name != 'pull_request_target' ||
       github.event.pull_request.head.repo.full_name == github.repository)
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Format with spotless
        run: ./gradlew spotlessApply

      - name: Delete empty files
        run: find $(git ls-files -m) -size 0 -delete

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: github.event_name != 'merge_group'
        with:
          commit_user_name: 'VoWBot'
          commit_user_email: 'admin@voicesofwynn.com'
          commit_message: 'ci: spotless formatting'

      - name: Build with Gradle
        run: ./gradlew buildDependents -x spotlessCheck -x test
