name: Sync Sounds to Azure
on:
  push:
    branches:
      - main
    paths:
      - "sounds/**"
  workflow_dispatch:

jobs:
  sync-to-blob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Identify changed and deleted files
        id: diff
        run: |
          CHANGED_FILES=$(git diff --diff-filter=ACM --name-only HEAD~1 HEAD -- sounds/ | tr '\n' ' ')
          DELETED_FILES=$(git diff --diff-filter=D --name-only HEAD~1 HEAD -- sounds/ | tr '\n' ' ')
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          echo "$CHANGED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "DELETED_FILES<<EOF" >> $GITHUB_ENV
          echo "$DELETED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV


      - name: Upload changed files to Azure Blob Storage
        if: env.CHANGED_FILES != ''
        env:
          BLOB_SAS_URL: ${{ secrets.BLOB_SAS_URL }}
        run: |
          containerUrl="${BLOB_SAS_URL%%\?*}"
          sasToken="${BLOB_SAS_URL#*\?}"
          for file in $CHANGED_FILES; do
            azcopy copy "$file" "${containerUrl}/sounds/${file#sounds/}?${sasToken}" --overwrite=true
          done

      - name: Delete removed files from Azure Blob Storage
        if: env.DELETED_FILES != ''
        env:
          BLOB_SAS_URL: ${{ secrets.BLOB_SAS_URL }}
        run: |
          containerUrl="${BLOB_SAS_URL%%\?*}"
          sasToken="${BLOB_SAS_URL#*\?}"
          for file in $DELETED_FILES; do
            azcopy remove "${containerUrl}/sounds/${file#sounds/}?${sasToken}" --recursive
          done
