name: Sync Sounds to Azure 
on:
  push:
    paths:
      - "sounds/**"
  workflow_dispatch:
jobs:
  sync-to-blob:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Upload sounds folder to Azure Blob Storage
      run: |
        azcopy copy './sounds/*' '${{ secrets.AZURE_STORAGE_URL }}' --recursive

        
