name: Upload All Sounds to Azure

on:
  workflow_dispatch:

jobs:
  upload-sounds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload all sound files to Azure Blob Storage
        run: |
          find sounds -type f | while read file; do
            azcopy copy "$file" "${{ secrets.AZURE_STORAGE_URL }}/$file"
          done
