name: Sync Sounds to Azure
on:
  push:
    paths:
      - "sounds/**"
  workflow_dispatch:

jobs:
  sync-to-blob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Identify changed files
        id: changed-files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD -- sounds/ | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Upload changed files to Azure Blob Storage
        if: env.CHANGED_FILES != ''
        env:
          BLOB_SAS_URL: ${{ secrets.BLOB_SAS_URL }}
        run: |
          # Split the SAS URL into the container URL and the SAS token
          containerUrl="${BLOB_SAS_URL%%\?*}"
          sasToken="${BLOB_SAS_URL#*\?}"
          for file in $CHANGED_FILES; do
            azcopy copy "$file" "${containerUrl}/sounds/${file#sounds/}?${sasToken}"
          done
